# sarenv/analytics/metrics.py
"""
Provides the PathEvaluator framework to quantify Unmanned Aerial Vehicle (UAV) trajectory 
performance against spatial probability arrays, temporal survival decay models, 
and overall geographical coverage bounds.
"""
import geopandas as gpd
import numpy as np
from scipy.interpolate import RegularGridInterpolator
from shapely.geometry import LineString, Point
from shapely.ops import unary_union


class PathEvaluator:
    """
    Evaluates multi-agent coverage paths against established wilderness search metrics,
    including cumulative likelihood acquisition, time-discounted probability, and 
    time-to-discovery triage thresholds.
    """

    def __init__(self, heatmap: np.ndarray, extent: tuple, victims: gpd.GeoDataFrame, fov_deg: float, altitude: float,
                 meters_per_bin: int):
        """
        Initialises the spatial evaluation framework and optical sensor constraints.

        Args:
            heatmap (np.ndarray): 2D probability array representing the search topography.
            extent (tuple): Geographical bounding box (minx, miny, maxx, maxy) of the evaluation space.
            victims (gpd.GeoDataFrame): Geospatial coordinates and severity attributes of simulated casualties.
            fov_deg (float): UAV optical sensor field of view.
            altitude (float): UAV operational altitude, determining the ground-plane sensor radius.
            meters_per_bin (int): Spatial resolution of the probability array cells.
        """
        self.heatmap = heatmap
        self.extent = extent
        self.victims = victims
        # Derives the mathematical radius of the ground sensor footprint via trigonometry
        self.detection_radius = altitude * np.tan(np.radians(fov_deg / 2))
        self.interpolation_resolution = int(np.ceil(meters_per_bin / 2))

        # Calculates precise grid cell dimensions for accurate raycasting/visibility checks
        minx, miny, maxx, maxy = self.extent
        self.heatmap_cell_size_x = (maxx - minx) / heatmap.shape[1]
        self.heatmap_cell_size_y = (maxy - miny) / heatmap.shape[0]

        y_range = np.linspace(miny, maxy, heatmap.shape[0])
        x_range = np.linspace(minx, maxx, heatmap.shape[1])
        self.interpolator = RegularGridInterpolator((y_range, x_range), heatmap, bounds_error=False, fill_value=0)

    def calculate_all_metrics(self, paths: list[LineString], discount_factor) -> dict:
        """
        Executes a comprehensive evaluation suite across the provided multi-agent paths, 
        calculating spatial likelihood acquisition and temporal discounting based on the sensor footprint.

        Args:
            paths (list[LineString]): The continuous geospatial routes generated by the routing algorithms.
            discount_factor (float, optional): The base penalty variable for time-dependent deterioration. Defaults to 0.999.

        Returns:
            dict: Compiled dictionary of aggregate performance and longitudinal metric arrays.
        """
        # Tracks globally observed probability cells to prevent overlapping agent redundancy
        globally_observed_cells = set()
        all_position_data = []
        path_metadata = []
        global_time_offset = 0

        # Pass 1: Discretize paths and map the optical visibility matrix
        for path_idx, path in enumerate(paths):
            if path.is_empty or path.length == 0:
                path_metadata.append({
                    'path_idx': path_idx,
                    'distances': np.array([0]),
                    'positions': [],
                    'global_distances': np.array([0]),
                    'visible_cells_per_position': []
                })
                continue

            num_points = int(np.ceil(path.length / self.interpolation_resolution)) + 1
            distances = np.linspace(0, path.length, num_points)
            points = [path.interpolate(d) for d in distances]
            positions = [(p.x, p.y) for p in points]

            global_distances = distances + global_time_offset

            visible_cells_per_position = []
            for x, y in positions:
                visible_cells = self.get_visible_cells(x, y)
                visible_cells_per_position.append(visible_cells)

            path_metadata.append({
                'path_idx': path_idx,
                'distances': distances,
                'positions': positions,
                'global_distances': global_distances,
                'visible_cells_per_position': visible_cells_per_position
            })

            for i, ((x, y), visible_cells) in enumerate(zip(positions, visible_cells_per_position, strict=True)):
                all_position_data.append({
                    'position': (x, y),
                    'visible_cells': visible_cells,
                    'path_idx': path_idx,
                    'position_idx': i,
                    'global_distance': global_distances[i]
                })

            global_time_offset += path.length

        # Pass 2: Aggregate global likelihoods using the non-redundant visibility model
        if all_position_data:
            all_observed_cells = set()
            for position_data in all_position_data:
                all_observed_cells.update(position_data['visible_cells'])

            total_likelihood = sum(self.heatmap[row, col] for row, col in all_observed_cells)

            total_time_discounted_score = 0
            for position_data in all_position_data:
                position_score = sum(self.heatmap[row, col] for row, col in position_data['visible_cells'])
                discount = discount_factor ** position_data['global_distance']
                total_time_discounted_score += position_score * discount
        else:
            total_likelihood = 0
            total_time_discounted_score = 0

        # Pass 3: Generate sequential cumulative tracking arrays for longitudinal analysis
        cumulative_distances_all_paths = []
        cumulative_likelihoods_all_paths = []
        cumulative_discounted_scores_all_paths = []

        for meta in path_metadata:
            if not meta['positions']:
                cumulative_distances_all_paths.append(np.array([0]))
                cumulative_likelihoods_all_paths.append(np.array([0]))
                cumulative_discounted_scores_all_paths.append(np.array([0]))
                continue

            path_observed_cells = set()
            path_likelihoods = []
            path_discounted_likelihoods = []

            for i, visible_cells in enumerate(meta['visible_cells_per_position']):
                new_cells = visible_cells - path_observed_cells
                path_observed_cells.update(new_cells)

                position_likelihood = sum(self.heatmap[row, col] for row, col in new_cells)
                discount = discount_factor ** meta['distances'][i]

                path_likelihoods.append(position_likelihood)
                path_discounted_likelihoods.append(position_likelihood * discount)

            cumulative_distances_all_paths.append(meta['distances'])
            cumulative_likelihoods_all_paths.append(np.cumsum(path_likelihoods))
            cumulative_discounted_scores_all_paths.append(np.cumsum(path_discounted_likelihoods))

        # Pass 4: Compile explicit geospatial and triage intersections
        victim_metrics = self._calculate_victims_found_score(paths)
        area_covered = self._calculate_area_covered(paths)
        total_path_length = self._calculate_total_path_length(paths)

        return {
            'total_likelihood_score': total_likelihood,
            'total_time_discounted_score': total_time_discounted_score,
            'victim_detection_metrics': victim_metrics,
            'area_covered': area_covered,
            'total_path_length': total_path_length,
            'cumulative_distances': cumulative_distances_all_paths,
            'cumulative_likelihoods': cumulative_likelihoods_all_paths,
            'cumulative_time_discounted_scores': cumulative_discounted_scores_all_paths,
        }

    def _calculate_victims_found_score(self, paths: list[LineString]) -> dict:
        """
        Executes spatial intersections to determine casualty discovery and applies an exponential 
        temporal decay function to calculate the time-weighted triage score.

        Returns:
            dict: Discovery percentage, absolute triage performance, and indexed casualty arrays.
        """
        valid_paths = [p for p in paths if not p.is_empty and p.length > 0]
        if not valid_paths or self.victims.empty:
            return {'percentage_found': 0, 'triage_score': 0, 'found_victim_indices': []}

        # Computes the total aggregate optical footprint to identify intersected casualties
        buffered_paths = [p.buffer(self.detection_radius) for p in valid_paths]
        coverage_area = unary_union(buffered_paths)
        del buffered_paths

        found_victims = self.victims[self.victims.within(coverage_area)]
        percentage_found = (len(found_victims) / len(self.victims)) * 100 if not self.victims.empty else 0

        triage_score = 0
        
        # Exponential deterioration constants calibrated to a 50,000m flight budget constraint
        DECAY_RATES = {
            'Stable': 0.999986,   # Base biological decay
            'Critical': 0.999908  # Accelerated trauma/environmental decay
        }

        # Evaluates the exact operational distance required to achieve sensor intersection
        for idx, victim in found_victims.iterrows():
            severity = victim.get('severity', 'Stable')
            gamma = DECAY_RATES.get(severity, 0.9999)

            discovery_distances = []

            for path in valid_paths:
                if path.distance(victim.geometry) <= (self.detection_radius + 0.01):
                    dist_along_path = path.project(victim.geometry)
                    discovery_distances.append(dist_along_path)

            if discovery_distances:
                actual_discovery_dist = min(discovery_distances)
            else:
                actual_discovery_dist = sum(p.length for p in valid_paths) / len(valid_paths)

            # Core Triage Function: Base Weight * (Deterioration Constant ^ Intersect Distance)
            score = 100 * (gamma ** actual_discovery_dist)
            triage_score += score

        return {
            'percentage_found': percentage_found,
            'triage_score': triage_score,
            'found_victim_indices': found_victims.index.tolist()
        }

    def _calculate_area_covered(self, paths: list[LineString]) -> float:
        """
        Calculates the continuous geospatial footprint of the UAV swarm, utilising 
        geometrical unions to eliminate overlapping observation redundancies.

        Args:
            paths (list[LineString]): The continuous geospatial agent routes.

        Returns:
            float: Total non-redundant area mapped, expressed in square kilometers.
        """
        valid_paths = [p for p in paths if not p.is_empty and p.length > 0]
        if not valid_paths:
            return 0.0

        buffered_paths = [path.buffer(self.detection_radius) for path in valid_paths]
        combined_coverage = unary_union(buffered_paths)
        del buffered_paths

        return combined_coverage.area / 1_000_000

    def _calculate_total_path_length(self, paths: list[LineString]) -> float:
        """
        Aggregates the physical flight distances across all operational agents.

        Args:
            paths (list[LineString]): The continuous geospatial agent routes.

        Returns:
            float: Cumulative flight trajectory length in kilometers.
        """
        valid_paths = [p for p in paths if not p.is_empty and p.length > 0]
        if not valid_paths:
            return 0.0

        total_length = sum(path.length for path in valid_paths)
        return total_length / 1000

    def get_visible_cells(self, x: float, y: float) -> set[tuple[int, int]]:
        """
        Derives the active grid intersection generated by the UAV sensor footprint 
        at a specific geospatial coordinate.

        Args:
            x (float): Agent X coordinate in world space.
            y (float): Agent Y coordinate in world space.

        Returns:
            set[tuple[int, int]]: Array of (row, col) grid coordinates actively observed.
        """
        minx, miny, maxx, maxy = self.extent

        radius_in_cells_x = int(np.ceil(self.detection_radius / self.heatmap_cell_size_x))
        radius_in_cells_y = int(np.ceil(self.detection_radius / self.heatmap_cell_size_y))

        center_col = int((x - minx) / self.heatmap_cell_size_x)
        center_row = int((y - miny) / self.heatmap_cell_size_y)

        visible_cells = set()

        for row in range(max(0, center_row - radius_in_cells_y),
                         min(self.heatmap.shape[0], center_row + radius_in_cells_y + 1)):
            for col in range(max(0, center_col - radius_in_cells_x),
                             min(self.heatmap.shape[1], center_col + radius_in_cells_x + 1)):

                cell_x = minx + (col + 0.5) * self.heatmap_cell_size_x
                cell_y = miny + (row + 0.5) * self.heatmap_cell_size_y

                distance = np.sqrt((cell_x - x) ** 2 + (cell_y - y) ** 2)
                if distance <= self.detection_radius:
                    visible_cells.add((row, col))

        return visible_cells

    def calculate_view_score_at_position(self, x: float, y: float, visited_cells: set[tuple[int, int]]) -> float:
        """
        Calculates the instantaneous likelihood score derived from an agent's current coordinates,
        enforcing a strict penalty on redundant (previously visited) cell observations.

        Args:
            x (float): Agent X coordinate.
            y (float): Agent Y coordinate.
            visited_cells (set): Historical array of previously mapped probability cells.

        Returns:
            float: The net likelihood value of newly observed probability distributions.
        """
        visible_cells = self.get_visible_cells(x, y)
        total_score = 0.0

        for row, col in visible_cells:
            if (row, col) not in visited_cells:
                total_score += self.heatmap[row, col]

        return total_score

    def calculate_metrics_at_distance_intervals(self, paths: list[LineString], discount_factor: float = 0.999,
                                                interval_distance: float = 500.0) -> dict:
        """
        Discretizes continuous geometries into equidistant temporal intervals to 
        facilitate longitudinal performance tracking and spatial rendering.

        Args:
            paths (list[LineString]): Full operational UAV routes.
            discount_factor (float): The temporal penalty decay parameter.
            interval_distance (float): Physical distance constraint separating evaluation ticks.

        Returns:
            dict: Sequential arrays of precomputed longitudinal metrics.
        """
        flat_paths = []
        for item in paths:
            if isinstance(item, list):
                flat_paths.extend(item)
            else:
                flat_paths.append(item)

        valid_paths = [p for p in flat_paths if hasattr(p, 'is_empty') and not p.is_empty and p.length > 0]
        if not valid_paths:
            return {
                'interval_metrics': [],
                'interval_distances': [],
                'interval_positions': [],
                'total_intervals': 0
            }

        max_path_length = max(path.length for path in valid_paths)
        total_intervals = int(np.ceil(max_path_length / interval_distance)) + 1

        interval_metrics = []
        interval_distances = []
        interval_position_list = []

        path_segments = []
        path_coordinates = [] 
        for path_idx, path in enumerate(valid_paths):
            segments = []
            coordinates = []
            for i in range(total_intervals):
                distance_along_path = i * interval_distance

                if distance_along_path <= path.length:
                    point = path.interpolate(distance_along_path)
                    point_coords = (point.x, point.y)

                    if distance_along_path == 0:
                        start_point = path.interpolate(0)
                        partial_path = LineString([start_point.coords[0], start_point.coords[0]])
                        path_coords_up_to_here = [start_point.coords[0]]
                    else:
                        num_points = max(10, int(distance_along_path / 50)) 
                        distances = np.linspace(0, distance_along_path, num_points)
                        points = [path.interpolate(d) for d in distances]
                        partial_path = LineString([(p.x, p.y) for p in points])
                        path_coords_up_to_here = [(p.x, p.y) for p in points]
                else:
                    partial_path = path
                    end_point = path.interpolate(path.length)
                    point_coords = (end_point.x, end_point.y)
                    distance_along_path = path.length
                    path_coords_up_to_here = list(path.coords)

                segments.append({
                    'distance': distance_along_path,
                    'position': point_coords,
                    'partial_path': partial_path
                })
                coordinates.append(path_coords_up_to_here)
            path_segments.append(segments)
            path_coordinates.append(coordinates)

        for interval_idx in range(total_intervals):
            partial_paths = []
            positions = []
            path_coords_for_interval = []

            for drone_idx, (segments, coordinates) in enumerate(zip(path_segments, path_coordinates)):
                if interval_idx < len(segments):
                    partial_paths.append(segments[interval_idx]['partial_path'])
                    positions.append(segments[interval_idx]['position'])
                    path_coords_for_interval.append(coordinates[interval_idx])
                else:
                    partial_paths.append(segments[-1]['partial_path'])
                    positions.append(segments[-1]['position'])
                    path_coords_for_interval.append(coordinates[-1])

            interval_position_list.append(positions)

            try:
                metrics_result = self.calculate_all_metrics(partial_paths, discount_factor)
                interval_metrics.append({
                    'area_covered': metrics_result.get('area_covered', 0),
                    'likelihood_score': metrics_result.get('total_likelihood_score', 0),
                    'victims_found_pct': metrics_result.get('victim_detection_metrics', {}).get('percentage_found', 0),
                    'triage_score': metrics_result.get('victim_detection_metrics', {}).get('triage_score', 0),
                    'total_path_length': metrics_result.get('total_path_length', 0),
                    'time_discounted_score': metrics_result.get('total_time_discounted_score', 0)
                })
            except Exception as e:
                if interval_metrics:
                    interval_metrics.append(interval_metrics[-1].copy())
                else:
                    interval_metrics.append({
                        'area_covered': 0, 'likelihood_score': 0, 'victims_found_pct': 0,
                        'total_path_length': 0, 'time_discounted_score': 0, 'triage_score': 0
                    })

            current_distance = interval_idx * interval_distance
            interval_distances.append(current_distance)

        return {
            'interval_metrics': interval_metrics,
            'interval_distances': interval_distances,
            'interval_positions': interval_position_list,
            'interval_path_coordinates': path_coordinates, 
            'total_intervals': total_intervals,
            'interval_distance_step': interval_distance
        }

    def calculate_metrics_at_intervals(self, paths: list[LineString], discount_factor: float = 0.999,
                                       interval_positions: int = 100) -> dict:
        """
        Discretizes paths geometrically rather than chronologically, enforcing regular 
        positional sampling to calculate sequential progression states.

        Args:
            paths (list[LineString]): Full operational UAV routes.
            discount_factor (float): The temporal penalty decay parameter.
            interval_positions (int): Absolute number of geometric evaluations required per route.

        Returns:
            dict: Sequential arrays of precomputed positional metrics.
        """
        flat_paths = []
        for item in paths:
            if isinstance(item, list):
                flat_paths.extend(item)
            else:
                flat_paths.append(item)

        valid_paths = [p for p in flat_paths if hasattr(p, 'is_empty') and not p.is_empty and p.length > 0]
        if not valid_paths:
            return {
                'interval_metrics': [],
                'interval_distances': [],
                'interval_positions': [],
                'total_intervals': 0
            }

        max_positions = 0
        path_coords = []
        for path in valid_paths:
            coords = list(path.coords)
            path_coords.append(coords)
            if isinstance(coords, list) and len(coords) > 0:
                max_positions = max(max_positions, len(coords))

        total_intervals = int(np.ceil(max_positions / interval_positions)) + 1

        interval_metrics = []
        interval_distances = []
        interval_position_list = [] 

        path_segments = []
        for path_idx, (path, coords) in enumerate(zip(valid_paths, path_coords)):
            segments = []
            for i in range(total_intervals):
                position_idx = min(i * interval_positions, len(coords) - 1)

                if position_idx < len(coords):
                    point_coords = coords[position_idx]

                    if position_idx == 0:
                        partial_path = LineString([coords[0], coords[0]])
                    else:
                        partial_coords = coords[:position_idx + 1]
                        partial_path = LineString(partial_coords) if len(partial_coords) > 1 else LineString(
                            [partial_coords[0], partial_coords[0]])

                    if position_idx == 0:
                        distance = 0
                    else:
                        temp_path = LineString(coords[:position_idx + 1])
                        distance = temp_path.length
                else:
                    partial_path = path
                    point_coords = coords[-1]
                    distance = path.length

                segments.append({
                    'distance': distance,
                    'position': point_coords,
                    'partial_path': partial_path,
                    'position_idx': position_idx
                })
            path_segments.append(segments)

        for interval_idx in range(total_intervals):
            partial_paths = []
            positions = []

            for drone_idx, segments in enumerate(path_segments):
                if interval_idx < len(segments):
                    partial_paths.append(segments[interval_idx]['partial_path'])
                    positions.append(segments[interval_idx]['position'])
                else:
                    partial_paths.append(segments[-1]['partial_path'])
                    positions.append(segments[-1]['position'])

            try:
                metrics_result = self.calculate_all_metrics(partial_paths, discount_factor)
                interval_metrics.append({
                    'area_covered': metrics_result.get('area_covered', 0),
                    'likelihood_score': metrics_result.get('total_likelihood_score', 0),
                    'victims_found_pct': metrics_result.get('victim_detection_metrics', {}).get('percentage_found', 0),
                    'triage_score': metrics_result.get('victim_detection_metrics', {}).get('triage_score', 0),
                    'total_path_length': metrics_result.get('total_path_length', 0),
                    'time_discounted_score': metrics_result.get('total_time_discounted_score', 0)
                })
            except Exception as e:
                if interval_metrics:
                    interval_metrics.append(interval_metrics[-1].copy())
                else:
                    interval_metrics.append({
                        'area_covered': 0, 'likelihood_score': 0, 'victims_found_pct': 0,
                        'total_path_length': 0, 'time_discounted_score': 0, 'triage_score': 0
                    })

            avg_distance = sum(path_segments[i][min(interval_idx, len(path_segments[i]) - 1)]['distance']
                               for i in range(len(path_segments))) / len(path_segments)
            interval_distances.append(avg_distance)
            interval_position_list.append(positions)

        return {
            'interval_metrics': interval_metrics,
            'interval_distances': interval_distances,
            'interval_positions': interval_position_list,
            'total_intervals': total_intervals,
            'interval_positions_step': interval_positions
        }
